name: FAcast
domain: https://facast.net
author: "Hayato Aokiba/Okada Genya"
description: フロントエンドと車の雑談Podcast
rss: https://facast.net/feed.xml
hashtag: FAcast
googleAnalytics: "UA-128245297-1"
storageUrl: "https://storage.googleapis.com/facast/storage/fileNumber.mp3"